apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
  namespace: bookInfo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo