apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infoapi
    layer: api
  name: infoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infoapi
  template:
    metadata:
      labels:
        app: infoapi
    spec:
      containers:
      - image: serdarkalayci/bookinfo-info:0.1
        name: bookinfo-api
        env:
        - name: BASE_URL
          value: ":5550"
        - name: STOCK_URL
          value: "http://stockapi:5555"
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: ConnectionString
          value: mongodb://{username}:{password}@mongodb:27017
        - name: DatabaseName
          value: bookInfo
        - name: DbUserName
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: username
        - name: DbPassword
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: password
        ports:
        - containerPort: 5550
        volumeMounts:
          - name: api-livesettings
            mountPath: /configuration
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5550
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 2
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
            httpGet:
              path: /healthz/live
              port: 5550
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 2
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
      volumes:
        - name: api-livesettings
          configMap:
            name: api-livesettings