version: '3.7'
services:
  bookinfoapi:
    build: ./bookInfoAPI/.
    container_name: bookInfoAPI
    ports:
      - "5550:5550"
    environment: 
      BASE_URL : ":5550"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: bookInfoAPI
      STOCK_URL: "http://bookstockapi:5555"
      ConnectionString: "mongodb://{username}:{password}@mongo:27017"
      DatabaseName: bookInfo
      DbUserName: mongoadmin
      DbPassword: secret
    networks:
      - bookInfo-network
  bookstockapi:
    build: 
      context: ./bookStockAPI/.
      dockerfile: v1.dockerfile
    container_name: bookStockAPI
    ports:
      - "5555:5555"
    environment: 
      BASE_URL : ":5555"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: bookStockAPI
      ConnectionString: "redis:6379"
      DatabaseName: 0
      DbPassword: secret
    networks:
      - bookInfo-network          
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bookinfo_jaeger
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - bookInfo-network      
  prometheus:
    build: prometheus/.
    container_name: bookinfo_prometheus
    networks:
      - bookInfo-network    
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on: 
      - prometheus  
    networks:
      - bookInfo-network      
  mongo:
    build: ./mongodb/.
    container_name: bookInfo-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: bookInfo
    volumes: 
      - bookinfo-mongodata:/data/db
    networks:
      - bookInfo-network
  mongo-express:
    image: mongo-express
    container_name: bookInfo-mexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongo:27017/
    depends_on: 
      - mongo
    networks:
      - bookInfo-network
  redis:
    build: ./redis/.
    container_name: bookInfo-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - bookinfo-redisdata:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - bookInfo-network      
networks:
  bookInfo-network:    
volumes:
  bookinfo-mongodata:
  grafana-storage:
  bookinfo-redisdata: