apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
    name: mongodb 
    namespace: bookInfo 
spec: 
    accessModes: 
    - ReadWriteOnce 
    resources: 
        requests: 
            storage: 1Gi 